In [2]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

In [4]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

Creating Arrays

In [5]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [6]:
type(my_list)

list

In [7]:
arr=np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [9]:
type(my_list)

list

In [10]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [11]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
np.arange(3.0)

array([0., 1., 2.])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
np.arange(20,10)

array([], dtype=int32)

In [17]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [18]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [19]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [20]:
np.arange(30,20)

array([], dtype=int32)

In [21]:
ar=np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [22]:
np.arange(10,10)

array([], dtype=int32)

In [23]:
np.arange()

TypeError: arange() requires stop to be specified.

In [24]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [25]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [26]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [27]:
np.zeros(3)

array([0., 0., 0.])

In [28]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [29]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [30]:
zero=np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [31]:
zerp=np.zeros([2,2])
print(zero)
print('###')
print(type(zero))

[[0. 0.]
 [0. 0.]]
###
<class 'numpy.ndarray'>


In [32]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [34]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [36]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [37]:
n=(6,7)
n1=(6,8)
print(np.zeros(n1)) #parameter tunning

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [38]:
print(np.zeros(n,dtype=int)) #hyperparameter tunning

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [39]:
n

(6, 7)

In [40]:
n1

(6, 8)

In [41]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [42]:
np.ones(3)

array([1., 1., 1.])

In [43]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [44]:
np.ones(4)

array([1., 1., 1., 1.])

In [45]:
n

(6, 7)

In [46]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [49]:
np.ones((5,4),dtype=int) #bydefault 5rows and 4 columns

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [50]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [51]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [52]:
np.three(2,3)

AttributeError: module 'numpy' has no attribute 'three'

In [53]:
np.ones(2)

array([1., 1.])

In [54]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [55]:
np.ones((6,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [56]:
np.twos((2,4))

AttributeError: module 'numpy' has no attribute 'twos'

In [57]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [58]:
np.three((2,4))

AttributeError: module 'numpy' has no attribute 'three'

In [59]:
range(5)

range(0, 5)

In [60]:
r=range(5)
r

range(0, 5)

In [61]:
for i in r:
    print(i)

0
1
2
3
4


In [62]:
list(range(5))

[0, 1, 2, 3, 4]

In [63]:
range(1,10)

range(1, 10)

In [64]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [65]:
list(range(1,10,3))

[1, 4, 7]

In [66]:
y=list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [67]:
rand(3,2)

NameError: name 'rand' is not defined

In [68]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [69]:
np.random.rand(5)

array([0.66856064, 0.37574173, 0.78004747, 0.23523628, 0.96990166])

In [70]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [71]:
np.random.rand(2,4)

array([[0.90845844, 0.3283083 , 0.58354652, 0.5937773 ],
       [0.92007071, 0.17799294, 0.65063875, 0.33181531]])

In [72]:
np.random.randint(2,4)

2

In [73]:
np.random.randint(2,20) #2nd argument is exclusive

3

In [74]:
np.random.randint(0,1)

0

In [75]:
np.random.randint(10,20,5)

array([14, 17, 16, 11, 13])

In [76]:
np.random.randint(1,6,4)

array([5, 2, 2, 4])

In [77]:
np.random.rand(3)

array([0.20847403, 0.17501181, 0.50384288])

In [78]:
np.random.randint(1)

0

In [79]:
np.random.randint(30,20,10)

ValueError: low >= high

In [80]:
np.random.randint(-30,20,10)

array([  4, -10, -28,  19, -20,   8,   7,  14,  13,  -3])

In [81]:
np.random.randint(20,30,10)

array([20, 22, 22, 26, 23, 20, 26, 21, 22, 26])

In [82]:
np.random.randint(5,9) #get the value<=1 and >=5

6

In [83]:
np.random.randint(10,21,3)

array([17, 20, 20])

In [84]:
np.random.randint(1,12,10)

array([ 8,  7,  9,  4,  6,  4,  6, 10,  7,  3])

In [85]:
np.random.randint(10,40,(10,10))

array([[26, 20, 39, 20, 12, 16, 32, 37, 15, 30],
       [11, 20, 14, 10, 18, 29, 22, 34, 32, 22],
       [18, 21, 39, 27, 20, 20, 22, 12, 24, 35],
       [38, 14, 39, 17, 30, 18, 32, 23, 25, 30],
       [14, 33, 12, 13, 31, 22, 32, 39, 34, 14],
       [25, 19, 34, 28, 26, 13, 21, 12, 27, 32],
       [13, 10, 20, 20, 20, 24, 10, 31, 36, 23],
       [32, 15, 14, 32, 16, 21, 31, 37, 35, 18],
       [31, 18, 38, 37, 20, 23, 13, 33, 30, 26],
       [36, 30, 23, 17, 36, 18, 29, 36, 30, 13]])

In [86]:
np.random.randint(1,100,(12,12))

array([[90, 94, 70, 99,  5, 35, 51, 79, 11, 18, 27, 41],
       [ 9, 77, 99, 17,  3, 80, 32, 44, 44, 29, 85, 91],
       [69, 94, 35, 37, 50,  4, 51, 13, 35,  6, 18, 14],
       [79, 75,  1, 26, 81, 99, 96, 51, 19, 53,  7, 23],
       [64, 59, 29, 51, 43, 52,  3, 46, 85, 28, 45, 97],
       [70, 74,  8, 45, 22, 32, 62, 53, 39, 98, 60, 87],
       [87, 67, 80, 51, 54, 43, 65, 98, 42, 54,  7, 83],
       [24, 40, 79, 24,  5, 34, 69,  7,  8, 15, 27, 36],
       [27, 60, 96,  4, 73, 45, 41, 56,  6, 90, 40, 65],
       [96, 23, 98, 29, 74, 46, 96, 81, 67, 11, 13, 70],
       [14, 28, 10, 11, 95, 61, 52, 67, 61, 73, 56,  8],
       [79, 95, 18, 89,  3, 88, 61, 81, 28,  2, 19, 66]])

In [87]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [88]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [89]:
b=np.random.randint(10,20,(5,4))
b

array([[16, 19, 10, 17],
       [15, 14, 17, 19],
       [13, 17, 13, 16],
       [10, 17, 11, 19],
       [16, 12, 11, 13]])

In [90]:
type(b)

numpy.ndarray

In [91]:
b

array([[16, 19, 10, 17],
       [15, 14, 17, 19],
       [13, 17, 13, 16],
       [10, 17, 11, 19],
       [16, 12, 11, 13]])

In [92]:
b[:]

array([[16, 19, 10, 17],
       [15, 14, 17, 19],
       [13, 17, 13, 16],
       [10, 17, 11, 19],
       [16, 12, 11, 13]])

In [93]:
b[1:3]

array([[15, 14, 17, 19],
       [13, 17, 13, 16]])

In [94]:
b

array([[16, 19, 10, 17],
       [15, 14, 17, 19],
       [13, 17, 13, 16],
       [10, 17, 11, 19],
       [16, 12, 11, 13]])

In [95]:
b[1,2]

17

In [96]:
b

array([[16, 19, 10, 17],
       [15, 14, 17, 19],
       [13, 17, 13, 16],
       [10, 17, 11, 19],
       [16, 12, 11, 13]])

In [97]:
b[1,3]

19

In [98]:
b[1,-1]

19

In [99]:
b

array([[16, 19, 10, 17],
       [15, 14, 17, 19],
       [13, 17, 13, 16],
       [10, 17, 11, 19],
       [16, 12, 11, 13]])

In [100]:
b[2:3]

array([[13, 17, 13, 16]])

In [101]:
b

array([[16, 19, 10, 17],
       [15, 14, 17, 19],
       [13, 17, 13, 16],
       [10, 17, 11, 19],
       [16, 12, 11, 13]])

In [102]:
b[0:-2]

array([[16, 19, 10, 17],
       [15, 14, 17, 19],
       [13, 17, 13, 16]])

In [103]:
b

array([[16, 19, 10, 17],
       [15, 14, 17, 19],
       [13, 17, 13, 16],
       [10, 17, 11, 19],
       [16, 12, 11, 13]])

In [104]:
b[0,2]

10

In [105]:
b

array([[16, 19, 10, 17],
       [15, 14, 17, 19],
       [13, 17, 13, 16],
       [10, 17, 11, 19],
       [16, 12, 11, 13]])

In [106]:
b[-5,-3]

19

In [107]:
b

array([[16, 19, 10, 17],
       [15, 14, 17, 19],
       [13, 17, 13, 16],
       [10, 17, 11, 19],
       [16, 12, 11, 13]])

In [108]:
b[-4,2]

17

In [109]:
np.random.randint(10,20,(4,4))

array([[13, 16, 12, 19],
       [14, 19, 17, 15],
       [17, 18, 13, 15],
       [16, 13, 15, 18]])

In [110]:
b

array([[16, 19, 10, 17],
       [15, 14, 17, 19],
       [13, 17, 13, 16],
       [10, 17, 11, 19],
       [16, 12, 11, 13]])

In [111]:
b[-4,-2]

17

In [112]:
b

array([[16, 19, 10, 17],
       [15, 14, 17, 19],
       [13, 17, 13, 16],
       [10, 17, 11, 19],
       [16, 12, 11, 13]])

In [113]:
b[-4:2]

array([[15, 14, 17, 19]])

In [114]:
b[:]

array([[16, 19, 10, 17],
       [15, 14, 17, 19],
       [13, 17, 13, 16],
       [10, 17, 11, 19],
       [16, 12, 11, 13]])

Operations

In [115]:
a=np.random.randint(10,20,10)
a

array([11, 18, 16, 16, 11, 13, 10, 16, 16, 16])

In [116]:
id(a)

2879115037552

In [117]:
arr

array([0, 1, 2, 3, 4, 5])

In [119]:
arr2=np.random.randint(0,100,(10,10))
arr2

array([[88, 88, 51, 81, 36, 36, 43, 24, 56, 93],
       [57, 83, 61, 44,  3, 94, 13, 54, 29, 20],
       [33,  1, 96, 14, 47, 18, 41, 79, 24, 87],
       [95, 18, 81, 49, 58, 59,  6, 68, 90, 63],
       [62, 47, 36, 35, 69, 79,  8, 53, 66, 82],
       [87, 18, 38, 13, 76, 85, 24, 14, 19,  3],
       [74, 15, 32, 90, 23, 19, 23,  8, 34, 80],
       [86,  7, 14, 49, 38, 47, 75,  9, 91, 43],
       [31, 13, 84, 85, 80, 22, 52, 24, 22, 14],
       [53, 22, 92, 21, 69, 94, 37, 32, 27, 57]])

In [120]:
arr

array([0, 1, 2, 3, 4, 5])

In [121]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [122]:
arr[:4]

array([0, 1, 2, 3])

In [123]:
arr2[:]

array([[88, 88, 51, 81, 36, 36, 43, 24, 56, 93],
       [57, 83, 61, 44,  3, 94, 13, 54, 29, 20],
       [33,  1, 96, 14, 47, 18, 41, 79, 24, 87],
       [95, 18, 81, 49, 58, 59,  6, 68, 90, 63],
       [62, 47, 36, 35, 69, 79,  8, 53, 66, 82],
       [87, 18, 38, 13, 76, 85, 24, 14, 19,  3],
       [74, 15, 32, 90, 23, 19, 23,  8, 34, 80],
       [86,  7, 14, 49, 38, 47, 75,  9, 91, 43],
       [31, 13, 84, 85, 80, 22, 52, 24, 22, 14],
       [53, 22, 92, 21, 69, 94, 37, 32, 27, 57]])

In [124]:
arr2[0:5]

array([[88, 88, 51, 81, 36, 36, 43, 24, 56, 93],
       [57, 83, 61, 44,  3, 94, 13, 54, 29, 20],
       [33,  1, 96, 14, 47, 18, 41, 79, 24, 87],
       [95, 18, 81, 49, 58, 59,  6, 68, 90, 63],
       [62, 47, 36, 35, 69, 79,  8, 53, 66, 82]])

In [125]:
arr2

array([[88, 88, 51, 81, 36, 36, 43, 24, 56, 93],
       [57, 83, 61, 44,  3, 94, 13, 54, 29, 20],
       [33,  1, 96, 14, 47, 18, 41, 79, 24, 87],
       [95, 18, 81, 49, 58, 59,  6, 68, 90, 63],
       [62, 47, 36, 35, 69, 79,  8, 53, 66, 82],
       [87, 18, 38, 13, 76, 85, 24, 14, 19,  3],
       [74, 15, 32, 90, 23, 19, 23,  8, 34, 80],
       [86,  7, 14, 49, 38, 47, 75,  9, 91, 43],
       [31, 13, 84, 85, 80, 22, 52, 24, 22, 14],
       [53, 22, 92, 21, 69, 94, 37, 32, 27, 57]])

In [129]:
arr2[1,4]

3

In [130]:
arr2

array([[88, 88, 51, 81, 36, 36, 43, 24, 56, 93],
       [57, 83, 61, 44,  3, 94, 13, 54, 29, 20],
       [33,  1, 96, 14, 47, 18, 41, 79, 24, 87],
       [95, 18, 81, 49, 58, 59,  6, 68, 90, 63],
       [62, 47, 36, 35, 69, 79,  8, 53, 66, 82],
       [87, 18, 38, 13, 76, 85, 24, 14, 19,  3],
       [74, 15, 32, 90, 23, 19, 23,  8, 34, 80],
       [86,  7, 14, 49, 38, 47, 75,  9, 91, 43],
       [31, 13, 84, 85, 80, 22, 52, 24, 22, 14],
       [53, 22, 92, 21, 69, 94, 37, 32, 27, 57]])

In [131]:
arr2[-5,5]

85

In [132]:
arr2[-5,-5]

85

In [133]:
arr2

array([[88, 88, 51, 81, 36, 36, 43, 24, 56, 93],
       [57, 83, 61, 44,  3, 94, 13, 54, 29, 20],
       [33,  1, 96, 14, 47, 18, 41, 79, 24, 87],
       [95, 18, 81, 49, 58, 59,  6, 68, 90, 63],
       [62, 47, 36, 35, 69, 79,  8, 53, 66, 82],
       [87, 18, 38, 13, 76, 85, 24, 14, 19,  3],
       [74, 15, 32, 90, 23, 19, 23,  8, 34, 80],
       [86,  7, 14, 49, 38, 47, 75,  9, 91, 43],
       [31, 13, 84, 85, 80, 22, 52, 24, 22, 14],
       [53, 22, 92, 21, 69, 94, 37, 32, 27, 57]])

In [134]:
arr2[-5,-5]

85

In [135]:
arr2

array([[88, 88, 51, 81, 36, 36, 43, 24, 56, 93],
       [57, 83, 61, 44,  3, 94, 13, 54, 29, 20],
       [33,  1, 96, 14, 47, 18, 41, 79, 24, 87],
       [95, 18, 81, 49, 58, 59,  6, 68, 90, 63],
       [62, 47, 36, 35, 69, 79,  8, 53, 66, 82],
       [87, 18, 38, 13, 76, 85, 24, 14, 19,  3],
       [74, 15, 32, 90, 23, 19, 23,  8, 34, 80],
       [86,  7, 14, 49, 38, 47, 75,  9, 91, 43],
       [31, 13, 84, 85, 80, 22, 52, 24, 22, 14],
       [53, 22, 92, 21, 69, 94, 37, 32, 27, 57]])

In [136]:
arr2[-1,-2]


27

In [137]:
arr2

array([[88, 88, 51, 81, 36, 36, 43, 24, 56, 93],
       [57, 83, 61, 44,  3, 94, 13, 54, 29, 20],
       [33,  1, 96, 14, 47, 18, 41, 79, 24, 87],
       [95, 18, 81, 49, 58, 59,  6, 68, 90, 63],
       [62, 47, 36, 35, 69, 79,  8, 53, 66, 82],
       [87, 18, 38, 13, 76, 85, 24, 14, 19,  3],
       [74, 15, 32, 90, 23, 19, 23,  8, 34, 80],
       [86,  7, 14, 49, 38, 47, 75,  9, 91, 43],
       [31, 13, 84, 85, 80, 22, 52, 24, 22, 14],
       [53, 22, 92, 21, 69, 94, 37, 32, 27, 57]])

In [138]:
arr2[::-1]

array([[53, 22, 92, 21, 69, 94, 37, 32, 27, 57],
       [31, 13, 84, 85, 80, 22, 52, 24, 22, 14],
       [86,  7, 14, 49, 38, 47, 75,  9, 91, 43],
       [74, 15, 32, 90, 23, 19, 23,  8, 34, 80],
       [87, 18, 38, 13, 76, 85, 24, 14, 19,  3],
       [62, 47, 36, 35, 69, 79,  8, 53, 66, 82],
       [95, 18, 81, 49, 58, 59,  6, 68, 90, 63],
       [33,  1, 96, 14, 47, 18, 41, 79, 24, 87],
       [57, 83, 61, 44,  3, 94, 13, 54, 29, 20],
       [88, 88, 51, 81, 36, 36, 43, 24, 56, 93]])

In [139]:
arr2

array([[88, 88, 51, 81, 36, 36, 43, 24, 56, 93],
       [57, 83, 61, 44,  3, 94, 13, 54, 29, 20],
       [33,  1, 96, 14, 47, 18, 41, 79, 24, 87],
       [95, 18, 81, 49, 58, 59,  6, 68, 90, 63],
       [62, 47, 36, 35, 69, 79,  8, 53, 66, 82],
       [87, 18, 38, 13, 76, 85, 24, 14, 19,  3],
       [74, 15, 32, 90, 23, 19, 23,  8, 34, 80],
       [86,  7, 14, 49, 38, 47, 75,  9, 91, 43],
       [31, 13, 84, 85, 80, 22, 52, 24, 22, 14],
       [53, 22, 92, 21, 69, 94, 37, 32, 27, 57]])

In [140]:
arr2[::-2]

array([[53, 22, 92, 21, 69, 94, 37, 32, 27, 57],
       [86,  7, 14, 49, 38, 47, 75,  9, 91, 43],
       [87, 18, 38, 13, 76, 85, 24, 14, 19,  3],
       [95, 18, 81, 49, 58, 59,  6, 68, 90, 63],
       [57, 83, 61, 44,  3, 94, 13, 54, 29, 20]])

In [141]:
arr2

array([[88, 88, 51, 81, 36, 36, 43, 24, 56, 93],
       [57, 83, 61, 44,  3, 94, 13, 54, 29, 20],
       [33,  1, 96, 14, 47, 18, 41, 79, 24, 87],
       [95, 18, 81, 49, 58, 59,  6, 68, 90, 63],
       [62, 47, 36, 35, 69, 79,  8, 53, 66, 82],
       [87, 18, 38, 13, 76, 85, 24, 14, 19,  3],
       [74, 15, 32, 90, 23, 19, 23,  8, 34, 80],
       [86,  7, 14, 49, 38, 47, 75,  9, 91, 43],
       [31, 13, 84, 85, 80, 22, 52, 24, 22, 14],
       [53, 22, 92, 21, 69, 94, 37, 32, 27, 57]])

In [142]:
arr2[::-3]

array([[53, 22, 92, 21, 69, 94, 37, 32, 27, 57],
       [74, 15, 32, 90, 23, 19, 23,  8, 34, 80],
       [95, 18, 81, 49, 58, 59,  6, 68, 90, 63],
       [88, 88, 51, 81, 36, 36, 43, 24, 56, 93]])

In [143]:
arr2

array([[88, 88, 51, 81, 36, 36, 43, 24, 56, 93],
       [57, 83, 61, 44,  3, 94, 13, 54, 29, 20],
       [33,  1, 96, 14, 47, 18, 41, 79, 24, 87],
       [95, 18, 81, 49, 58, 59,  6, 68, 90, 63],
       [62, 47, 36, 35, 69, 79,  8, 53, 66, 82],
       [87, 18, 38, 13, 76, 85, 24, 14, 19,  3],
       [74, 15, 32, 90, 23, 19, 23,  8, 34, 80],
       [86,  7, 14, 49, 38, 47, 75,  9, 91, 43],
       [31, 13, 84, 85, 80, 22, 52, 24, 22, 14],
       [53, 22, 92, 21, 69, 94, 37, 32, 27, 57]])

In [144]:
arr2[:-3]

array([[88, 88, 51, 81, 36, 36, 43, 24, 56, 93],
       [57, 83, 61, 44,  3, 94, 13, 54, 29, 20],
       [33,  1, 96, 14, 47, 18, 41, 79, 24, 87],
       [95, 18, 81, 49, 58, 59,  6, 68, 90, 63],
       [62, 47, 36, 35, 69, 79,  8, 53, 66, 82],
       [87, 18, 38, 13, 76, 85, 24, 14, 19,  3],
       [74, 15, 32, 90, 23, 19, 23,  8, 34, 80]])

In [145]:
arr2[:-3]

array([[88, 88, 51, 81, 36, 36, 43, 24, 56, 93],
       [57, 83, 61, 44,  3, 94, 13, 54, 29, 20],
       [33,  1, 96, 14, 47, 18, 41, 79, 24, 87],
       [95, 18, 81, 49, 58, 59,  6, 68, 90, 63],
       [62, 47, 36, 35, 69, 79,  8, 53, 66, 82],
       [87, 18, 38, 13, 76, 85, 24, 14, 19,  3],
       [74, 15, 32, 90, 23, 19, 23,  8, 34, 80]])

In [146]:
arr

array([0, 1, 2, 3, 4, 5])

In [147]:
arr.max()

5

In [148]:
arr.min()

0

In [149]:
arr

array([0, 1, 2, 3, 4, 5])

In [150]:
arr.mean()

2.5

In [151]:
arr

array([0, 1, 2, 3, 4, 5])

In [152]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [153]:
from numpy import*
a=array([1,2,3,4,9])
median(a)

3.0

Reshape

In [154]:
arr

array([0, 1, 2, 3, 4, 5])

In [155]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [156]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [157]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [158]:
arr

array([0, 1, 2, 3, 4, 5])

In [159]:
arr.reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [160]:
arr

array([0, 1, 2, 3, 4, 5])

In [161]:
arr.reshape(2,3,order='C')

array([[0, 1, 2],
       [3, 4, 5]])

In [162]:
arr.reshape(2,3,order='F') #print element with fortran

array([[0, 2, 4],
       [1, 3, 5]])

In [163]:
arr.reshape(2,3,order='A')

array([[0, 1, 2],
       [3, 4, 5]])

In [164]:
arr

array([0, 1, 2, 3, 4, 5])

In [165]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [166]:
arr.reshape(1,4)

ValueError: cannot reshape array of size 6 into shape (1,4)

In [167]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [168]:
arr.reshape(2,6)

ValueError: cannot reshape array of size 6 into shape (2,6)

In [169]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [170]:
arr

array([0, 1, 2, 3, 4, 5])

In [171]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

Indexing

In [172]:
mat=np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [173]:
row=4
col=5
col

5

In [174]:
row

4

In [175]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [176]:
mat[row,col]

45

In [178]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [179]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [180]:
col=6

In [181]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [182]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [183]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [184]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [185]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [186]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [187]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [188]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [189]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [190]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [191]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [192]:
row

4

In [193]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [195]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [196]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [197]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [198]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [200]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [201]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [202]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [203]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [204]:
row

4

In [205]:
col

6

In [207]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [208]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [209]:
mat[1,4]

14

In [210]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [211]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [212]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [213]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [214]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [215]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [216]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [217]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [218]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [219]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [220]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [221]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [222]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [223]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [224]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [225]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [226]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [227]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [228]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [229]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [230]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [231]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [232]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [233]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [234]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [235]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [236]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [237]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [238]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [239]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [241]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [242]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [243]:
mat[0,1]

1

In [245]:
mat[1,6]

16

In [246]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [247]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [248]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [249]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [250]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [251]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [252]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [253]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [254]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [255]:
mat[1:2,2:4]

array([[12, 13]])

In [256]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [257]:
mat[2:3,2:3]

array([[22]])

In [258]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [259]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [260]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [261]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [262]:
mat[2:3,4:5]

array([[24]])

Masking

In [263]:
mat # we also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [264]:
id(mat)

2879115220656

In [265]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [266]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [267]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [268]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [269]:
mat[mat==50]

array([50])

In [270]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [271]:
mat==50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [272]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [274]:
a1=mat[mat<50]
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [275]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [277]:
a2=mat[mat>50]
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [279]:
a3=mat[mat<=50]
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [280]:
a4=mat[mat==50]
a4

array([50])